[package]
name = "sf6rs"
version = "0.1.0"
edition = "2021"
authors = ["sagan"]

[dependencies]
regex = "1.10.4"
scraper = "0.19.0"
tokio = { version = "1.37.0", features = ["full"] }
reqwest = "0.12.4"
